spring:
  security:
    saml2:
      relyingparty:
        registration:
          auth0:
            signing:
              credentials: &signing-credentials
                - private-key-location: classpath:local.key
                  certificate-location: classpath:local.crt
            singlelogout: &logout-settings
              binding: POST
              response-url: "{baseUrl}/logout/saml2/slo"
            assertingparty:
              metadata-uri: https://dev-06bzs1cu.us.auth0.com/samlp/metadata/wfFEjnhej7wt29jxUWM8lIHjCndf3qSS
          okta:
            signing:
              credentials: *signing-credentials
            singlelogout: *logout-settings
            assertingparty:
              metadata-uri: https://dev-17700857.okta.com/app/exk61utspt4rSUV9J5d7/sso/saml/metadata
